### ISSUE TITLE
turbobench doesn't work

### ISSUE THREAD

**Issue by flip111** [powturbo/TurboBench#13]
I have a i3-4005U cpu, running ubuntu 16.04. I just tried to clone and run this program, with the command `./turbobench -p2 -S2 file.tbb &> error_output.txt` then the program aborts with exit code 255 and the output of error_output.txt is `<86> <AD><FB>` (`less` puts `<` and `>` with hexcode instead of showing raw characters). `file.tbb` was not written

**Comment by powturbo** [comment]
file.tbb is the turbobench result file after benchmarking and is generated by turbobench. 
Please read the "README" file.

**Comment by flip111** [comment]
I want to get the `file.tbb` file with the results. But it's not written by turbobench. Please reopen the issue.

**Comment by powturbo** [comment]
Here an example:
./turbobench -ebrotli,6/zlib,6 myfile
will generate the result file "myfile.tbb"
The result file "myfile.tbb" is always generated. The only exception is when turbobench crashes.

- write the result to the console:
./turbobench -p1 -o myfile.tbb

- generate a html result file for browsing:
./turbobench -p2 -S2 myfile.tbb
will generate the file "myfile.tbb.html"

**Comment by flip111** [comment]
Ah i got it to work now. I was confused by the wording in the readme:

I was looking at this command `./turbobench -p2 -S2 file.tbb`
And it says "Print result file" .. so i think i get to see a result file.

Also this is under the "Testing" header. So i think a new result file will be generated.

But actually i had to generate a result file first with other commands before being able to generate that html file.

It would still be better to say something like "input benchmark file not found" when trying to generate a html from a file that does not exist.

I have another question .. which command can i use to test all possible codecs ?

**Comment by flip111** [comment]
ping @powturbo is there a command to test all possible codecs and their settings? i didn't want to open a new issue for it to ask ..

**Comment by powturbo** [comment]
No. This will take too long to finnish. 
You can however define your own codec grouo in the "turbobench.ini" file.
