### ISSUE TITLE
add codecs

### ISSUE THREAD

**Issue by flip111** [powturbo/TurboBench#14]
It would be interesting to add codecs

libzlf
lzfx
lz88
aPlib
delta encoding
runlength encoding
zstandard

all but the last one are potentially useful in use on low power microcontrollers

**Comment by powturbo** [comment]
liblzf, runlength encoding (turborle), zstandard (zstd) are already included.
Only competitive compressors will be included in the future.
It is simple to include your own or your preferred coded into turbobench.

**Comment by flip111** [comment]
Competitive by which standard ? These are all competitive when taking in mind the constrains a microcontroller gives you.

**Comment by powturbo** [comment]
If you have a competitive compressor, then please provide a link to the source code.
I'll check that.

**Comment by flip111** [comment]
lzfx https://code.google.com/archive/p/lzfx/

lz78
* https://github.com/AlessandroMartinelli/LZ78
* https://github.com/thecellarguardian/lz78
* https://github.com/evilaliv3/lz78
* https://github.com/jhallen/joes-sandbox/blob/master/compression/lz78.c
* https://gist.github.com/MajedSiefALnasr/32cff52b01d764ee158f2c36e4e84d95
* https://github.com/srahimeen/LZ78
* https://github.com/alexbeutel/LZ78

aPlib http://ibsensoftware.com/products_aPLib.html

delta encoding - is usually used together with another algorithm. It's widely used but i can't find a single project that is suitable to test this now

**Comment by powturbo** [comment]
I can't see a competitive, popular or innovative compressor here.
lzfx is old ant not maintained. It is derived from the already included liblzf
aPLib is very old. The newer Brieflz from the same author is already included.
None of the lz78 compressors is popular or competitive with lz77  
Most of the lz78 codecs are for education or for demonstration purposes and are not maintained.
Hopefully you understand, I can't see the sense to include more codecs now.

It is also simple to include your own or your preferred coded into turbobench.
Only plugin.cc (search for MYCODEC) and the makefile must be changed.

**Comment by flip111** [comment]
Ok thank you for your consideration and your perspective on these codes.
(Can't close from email)
