### ISSUE TITLE
Question about colon and mf=

### ISSUE THREAD

**Issue by flip111** [powturbo/TurboBench#19]
I saw in `turbobench.ini` the following line `LZMA9Z    lzma,9mt2:d29:a1:fb273:mf=bt4:mc999:lc8:lp0:pb2`

What is the meaning of the colon `:` and `mf=`? Also where can i read about what things like `pb` mean and what numbers after that are accepted?

**Comment by powturbo** [comment]
String after "lzma,9" contains parameters specfic to lzma (see [lzma documentation](https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm)
The colon is a separator for parameters. mf = match finder type.

**Comment by flip111** [comment]
Thanks for your answer that explains it. Would you consider an addition to the readme to say that extra parameters can be passed to algorithms?

**Comment by powturbo** [comment]
readme updated w/ a short note
