### ISSUE TITLE
Suggestions for Codecs

### ISSUE THREAD

**Issue by bleuge** [powturbo/TurboBench#28]
Are you interested in adding new codecs? 
I've been testing lately a lot of compressors specific for short strings, some suggestions 
- shoco
- smaz
- unishox

If you are interested in more of these I can dig my archives.

Turbobench is marvellous testing tool, many thanks for creating it!

**Comment by powturbo** [comment]
- shoco is already included (manual download + uncomment SHOCO=1 in the makefile)
- unishox now included (manual download + uncomment UNISHOX=1 in the makefile),
  unishox is too slow at compression even for short files  
- smaz is outdated, no plans to add it.

**Comment by bleuge** [comment]
Ok, thanks!
