### ISSUE TITLE
Is Oodle benchmarking supported?

### ISSUE THREAD

**Issue by theberrigan** [powturbo/TurboBench#29]
Oodle is on the plugin list, but when I try to use it error occurs:
> $ ./turbobench.exe ./data/big_building.ppm -eoodle,89
> codec 'oodle' not found

I have dlls in turbobench.exe directory: 
> oo2core_4_win64.dll
> oo2core_6_win64.dll
> oo2core_7_win64.dll
> oo2core_8_win64.dll

Windows 10 x64, Turbobench latest release.
Thanks.

**Comment by powturbo** [comment]
Support for oodle is no longer supported

**Comment by powturbo** [comment]
oodle is now included again. Now for windows + linux. You must put the dll or shared library library into the turbobench directory.
Actually you must build turbobench from the sources.
