### ISSUE TITLE
Printing to other formats with `-p' doesn't seem to work.

### ISSUE THREAD

**Issue by tansy** [powturbo/TurboBench#31]
I tried to print to cvs or markdown (with \`-p7') but it didn't work. Actually any format makes it to exit without any action.
I tried to fix it but didn't get far. All I got to is that \`printfile()' exits at `if(!k) return;` as \`plugread()' returns 0.

**Comment by powturbo** [comment]
It is working for me with:
turbobench -p7 file.tar.tbb
a "file.tsv" file is created
You must specify the ".tbb" previously generated by turbobench.
