### ISSUE TITLE
Option - b is invalid for fse and fsehuf

### ISSUE THREAD

**Issue by huhu0823** [powturbo/TurboBench#39]
1K：-b1k
./turbobench ../dataset/book -efsehuf -b1k
 851499254    79.3     681.55    1003.72   fsehuf 
-----------------------------------------------------------------------
4k：-b4k
./turbobench ../dataset/book -efsehuf -b4k
851499254    79.3     681.85    1002.65     855.22   fsehuf

**Comment by powturbo** [comment]
-b is the general block size in turbobench.

- use the option -Y for ANS (like fse)
- use -Z for fsehuf (ex. -Z32k )

Not sure what the minimum possible block size. There is no checking in Turbobench

**Comment by huhu0823** [comment]
Thank you very much. I hope the options for these compression algorithms can be unified in the future.
