### ISSUE TITLE
Support ZSTD's dictionary compression

### ISSUE THREAD

**Issue by psyduffy** [powturbo/TurboBench#42]
Does TurboBench support the ZSTD dictionary compression performance test? I want to try to compare the performance of ZSTD compression use the dictionary with other algorithms in small data mode.

**Comment by powturbo** [comment]
- benchmarking zstd with external dictionary
1 - generate a dictionary file with:
zstd --train mysamples/* -o mydic
2 - start turbobench with:
./turbobench -ezstd,22Dmydic file

actually the external dictionary "mydic" must be in the current directoy


You can also benchmark multiple small files using multiblock mode in turbobench:
1 - store your small files into a multiblock file using option "M"
./turbobench -Mmymultiblock files
(mymultiblock output format: length1,file1,length2,file2,...lengthN,fileN, length=4 bytes file/block length)
2 - Benchmark using option "-m" :
./turbobench -ezstd,22Dmydic mymultiblock -m

**Comment by powturbo** [comment]
The format of a block is : 
- 32 bits integer, block length (corresponding the file length of each file)
- data

You can create small multiblock files  (for ex. with 10.000 files each) and (binary) concatenate these files into one single big file.
