### ISSUE TITLE
bwt preset segfaults the program

### ISSUE THREAD

**Issue by GhostDog98** [powturbo/TurboBench#44]
Running `./turbobench -eBWT ascii.txt`
We can see we can do the first two items in the test:
        1576     8.9      42.84     261.86   bzip2            ascii.txt
        1347     7.6      40.68       0.03   bzip3            ascii.txt

But after that, we get a segfault:
Segmentation fault (core dumped)

Running Arch and the latest release.

**Comment by powturbo** [comment]
"BWT" is translated to "bsc_st,4,5/bsc,2/bcm/bzip2/bzip3/turborc,20e8,20e9/memcpy"
The segfault is ocurring in TurboRC.
I've tested this with several files and it working without crashing and I can't reproduce the issue on my pc.
