### ISSUE TITLE
Testing against Facebook's zstandard

### ISSUE THREAD

**Issue by searchivarius** [powturbo/TurboBench#6]
Would be interesting to see results:
https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard/
Thanks!

**Comment by powturbo** [comment]
You can download [Turbobench for windows or linux](https://sites.google.com/site/powturbo/downloads) and make your own tests with your data.
see also:
- [fastest compressors intel i7](http://encode.ru/threads/2221-LZFSE-New-Apple-Data-Compression)
- [TurboBench ARM 64 bits](https://github.com/powturbo/TurboBench)

**Comment by searchivarius** [comment]
Sure, but you are the master who knows this best. I thought that it might be interesting to you to demonstrate how well your software fares against a recently proposed strong benchmark.
