### ISSUE TITLE
Naka compilation error

### ISSUE THREAD

**Issue by dhdl** [powturbo/TurboBench#8]
When compiling from a pristine clone I'm getting the following error:
```
plugins.o: In function `codcomp':
plugins.cc:(.text+0x1ce1): undefined reference to `NakaCompress'
plugins.o: In function `coddecomp':
plugins.cc:(.text+0x32aa): undefined reference to `NakaDecompress'
collect2: error: ld returned 1 exit status
make: *** [makefile:436: turbobench] Error 1
```

**Comment by Sanmayce** [comment]
Would like to help you but don't know how to solve the issue, hope powturbo finds time to help you.
In the meantime you can check out the strongest&latest variant - 'Ryuugan+':
https://drive.google.com/file/d/0BzKgu_YpO6uZYnpGY0d0NHNHQWc/view?usp=sharing
https://drive.google.com/file/d/0BzKgu_YpO6uZb1VsSC02cE9WUlk/view?usp=sharing

**Comment by powturbo** [comment]
type 
"delete plugins.o" or "make clean"
and type 
"make" 
again without any option

if the problem persists, then disable Nakamichi by changing
"#define C_NAKA	    COMP2"
to
"#define C_NAKA	    0"
in the file plugins.cc"
