### ISSUE TITLE
Windows static binary

### ISSUE THREAD

**Issue by sergeevabc** [powturbo/TurboBench#9]
Dear @powturbo,
Could you be so kind to generate static ```.exe``` for the rest of us who have no various ```lib*.dll``` libraries?

**Comment by powturbo** [comment]
you can use the program "turbobenchs" from the download link. No external library is required.

**Comment by sergeevabc** [comment]
```turbobenchs.exe``` crashes right after launch on Windows 7 x64 (see [log][1] for details).

[1]: https://ghostbin.com/paste/xxuww

**Comment by powturbo** [comment]
Witch CPU are using? I think you must have a sandy bridge cpu or newer.

**Comment by sergeevabc** [comment]
I replied your question via [screenshot][1], link expires after being accessed once.

[1]: https://file.io/11aOeT

**Comment by powturbo** [comment]
This is the reason, sorry. You must have as a minimum a core2 cpu (better >= Sandy bridge), otherwise you must compile turbobench yourself using a mingw64 compiler.

**Comment by sergeevabc** [comment]
Screenshot clearly states the processor has 2 cores, what do you mean?

**Comment by sergeevabc** [comment]
Nevermind, I get it.
